const { app, BrowserWindow } = require('electron');
const path = require('path');
const { spawn } = require('child_process');

// ONLY declare the variable here, do NOT call 'new BrowserWindow' yet
let mainWindow;
let apiProcess = null;

/**
 * Forcefully terminates the Python API process on Windows.
 * Standard apiProcess.kill() often leaves "orphan" processes.
 */
const killPython = () => {
    if (apiProcess) {
        if (process.platform === 'win32') {
            // /f = force, /t = tree (kills child processes too)
            spawn('taskkill', ['/pid', apiProcess.pid, '/f', '/t']);
        } else {
            apiProcess.kill();
        }
        apiProcess = null;
    }
};

function createWindow() {
    mainWindow = new BrowserWindow({
        title: "Madhan Pawn Shop", 
        icon: path.join(__dirname, 'build', 'icon.ico'),
        width: 1280,
        height: 800,
        webPreferences: {
            nodeIntegration: true,
            contextIsolation: false
        }
    });

    // Remove the default menu bar for a professional desktop look
    mainWindow.setMenuBarVisibility(false);

    if (app.isPackaged) {
        // Points to the dist folder generated by your build
        mainWindow.loadFile(path.join(__dirname, 'dist', 'index.html'));
    } else {
        // In development, load the Vite dev server
        mainWindow.loadURL('http://localhost:5173');
    }

    mainWindow.on('closed', () => {
        mainWindow = null;
    });
}

function startPythonApi() {
    if (app.isPackaged) {
        // Path for the compiled backend inside the resources folder
        const apiPath = path.join(process.resourcesPath, 'pawnshop_api.exe');
        
        try {
            apiProcess = spawn(apiPath);
            
            apiProcess.stdout.on('data', (data) => console.log(`API: ${data}`));
            apiProcess.stderr.on('data', (data) => console.error(`API Error: ${data}`));
            
            apiProcess.on('error', (err) => {
                console.error("Failed to start API process:", err);
            });
        } catch (err) {
            console.error("Critical error spawning API:", err);
        }
    } else {
        console.log("Running in dev mode. Ensure uvicorn is running on port 8000.");
    }
}

// THE CORRECT LIFECYCLE: Wait for ready, then start API, then create Window
app.whenReady().then(() => {
    startPythonApi();
    createWindow();

    app.on('activate', () => {
        if (BrowserWindow.getAllWindows().length === 0) createWindow();
    });
});

// Safely kill the Python server when the user is quitting the app
app.on('before-quit', () => {
    killPython();
});

// Ensures the API dies when all windows are closed
app.on('window-all-closed', () => {
    killPython();
    if (process.platform !== 'darwin') {
        app.quit();
    }
});